/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login.vista;

import Login.logic.UsuarioLogic;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static  FrmLogin loginFull;

    /**
     * Creates new form LoginFull
     */
    public FrmLogin() {
        initComponents();
        this.setTitle("GAME STORE COL");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/store.png"));
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);
    }
    
    public static FrmLogin getInstance(){
        if(loginFull == null)
            loginFull=new FrmLogin();        
        return loginFull;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        chkMostrarContrasenia = new javax.swing.JCheckBox();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnOlvidasteContra = new javax.swing.JButton();
        lblCandado = new javax.swing.JLabel();
        lblElemento3 = new javax.swing.JLabel();
        lblIconoStore = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblUsuario1 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        lblElemento1 = new javax.swing.JLabel();
        lblElemento2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContrasenia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        lblContrasenia.setText("Contraseña:");
        jPanel2.add(lblContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, 30));

        txtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseniaActionPerformed(evt);
            }
        });
        jPanel2.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 370, 40));

        chkMostrarContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        chkMostrarContrasenia.setText("Mostrar contraseña");
        chkMostrarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarContraseniaActionPerformed(evt);
            }
        });
        jPanel2.add(chkMostrarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lblUsuario.setText("Usuario:");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 60, 30));
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 370, 40));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 370, 40));

        btnIngresar.setBackground(new java.awt.Color(0, 153, 51));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 370, 40));

        btnOlvidasteContra.setForeground(new java.awt.Color(116, 120, 141));
        btnOlvidasteContra.setText("¿Olvidaste la contraseña?");
        btnOlvidasteContra.setBorder(null);
        btnOlvidasteContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidasteContraActionPerformed(evt);
            }
        });
        jPanel2.add(btnOlvidasteContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, 40));

        lblCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lock.png"))); // NOI18N
        jPanel2.add(lblCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, 20));

        lblElemento3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Avatar_Container.png"))); // NOI18N
        jPanel2.add(lblElemento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 90));

        lblIconoStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoStore.jpg"))); // NOI18N
        jPanel2.add(lblIconoStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 280, 140));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Card_Content.png"))); // NOI18N
        lblFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 460));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitulo.setText("!Bienvenido(a)!");
        jPanel2.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 80));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextField1.setText("Para continuar, inicia sesión.");
        jTextField1.setBorder(null);
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 170, 50));

        lblUsuario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(153, 153, 153));
        lblUsuario1.setText("Usuario");
        jPanel2.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 60, 30));

        lblFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Card_Content.png"))); // NOI18N
        lblFondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 460));
        jPanel2.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 450, 600));

        lblElemento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Union.png"))); // NOI18N
        jPanel1.add(lblElemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 970, 600));

        lblElemento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ellipse.png"))); // NOI18N
        jPanel1.add(lblElemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 310, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jMenu1.setText("Opciones");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrito.png"))); // NOI18N
        jMenu3.setText("Ir al carrito");
        jMenu1.add(jMenu3);

        jMenu4.setText("Registrarse");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOlvidasteContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidasteContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOlvidasteContraActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void txtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseniaActionPerformed

    private void chkMostrarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarContraseniaActionPerformed
        // TODO add your handling code here:
        if(chkMostrarContrasenia.isSelected()){
            txtContrasenia.setEchoChar((char)0);
        }else{
            txtContrasenia.setEchoChar('*');
        }
    }//GEN-LAST:event_chkMostrarContraseniaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if(!txtUsuario.getText().isEmpty()&&!txtContrasenia.getText().isEmpty()){
            if(UsuarioLogic.autentificar(txtUsuario.getText(), txtContrasenia.getText())){
                JOptionPane.showMessageDialog(this, "Bienvenido a GameStoreCol");
                this.dispose();
                GameStoreCOL gameStoreCOL= new GameStoreCOL();
                gameStoreCOL.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Falta ingresar usuario o contraseña");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        FrmRegistrarUsuario frmRegistrarUsuario= new FrmRegistrarUsuario(this, true);
        frmRegistrarUsuario.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnOlvidasteContra;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkMostrarContrasenia;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCandado;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblElemento1;
    private javax.swing.JLabel lblElemento2;
    private javax.swing.JLabel lblElemento3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblIconoStore;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
